let x = 10;
let y = "10";
console.log(x == y);
console.log(x === y);
console.log(x != y);
console.log(x !== y);
console.log(x > 5);
console.log(x <= 10);
console.log(x && y);
console.log(x || null);
console.log(!false);
console.log(x % 3);
console.log(x + 5);
console.log(x - 3);
console.log(x * 2);
console.log(x / 2);